### ISSUE TITLE
Are rail Live dots too big for low zoom level?

### ISSUE THREAD

**Issue by kylerchin** [catenarytransit/catenary-frontend#19]
I really like the new interface style! I've made some slight changes to improve visual accessibility.

I don't have a screenshots right now since the backend is missing a lot of data, I will try this tomorrow. I think the dots for rail are a bit too big, especially on desktop below zoom level 10. For rail dense areas such as the EU, it could create extreme crowding. I don't have proof for this yet, this is a hunch as of now.

CC: @samuelbeepdev

**Comment by samuelbeepdev** [comment]
Hi Kyler, glad you like the new style. The rail dots were intentionally made very large to avoid conflict with bus and make route colors more clear (given that urban rail is often identified by color instead of designation). While I normally wouldn't suggest making changes app-wide just to accommodate European data, I'm open to any specific suggestions

**Comment by kylerchin** [comment]
This issue is now resolved! :) Shrank the size outside North America
![image](https://github.com/catenarytransit/catenary-frontend/assets/7539174/653ee077-af08-4002-a75f-ff4d0fca1c82)
